src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?bool $is_published = false;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Post $post = null;


    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\PostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home', methods: ['GET'])]
    public function index(PostRepository $repo): Response
    {
        $posts = $repo->findPosts();

        return $this->render('pages/home/index.html.twig', [
            'posts' => $posts
        ]);
    }
}

templates/pages/home/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Blog - Home{% endblock %}
{% block body %}
    <section>
        <div class="max-w-3xl mx-auto mt-8 border-b border-black dark:border-white">
                <h2 class="font-semibold text-3xl">Bella, ragà! ✌️</h2>
            <p class="mt-8 text-lg home-text">Blog è un blog tec focalizzato principalmente sul linguaggio PHP e sullo sviluppo con il framework Symfony. Pubblico qui concetti o elementi interessanti che ho esplorato. Cerco di approfondirle condividendo qui le mie scoperte.</p>
            <div class="my-8 text-lg flex items-center home-social">
                <span class="mr-6 font-bold">Social Links:</span>
                {% include "components/_social-link.html.twig" %}
            </div>
        </div>
    </section>
    <section>
        <div class="mx-auto max-w-3xl ">
            <h1 class="text-2xl mb-8 mt-12 font-bold">Ultimi posts</h1>
            <ul class="my-4">
                {% for post in posts | slice(0, 5) %}
                    <li class="my-8">
                        <a href={{ path('app_post_show', { slug : post.slug }) }}><h2 class="font-semibold text-rose-900 dark:text-cyan-400 text-xl mb-1">{{ post.title }}</h2></a>
                        <div class="dark:text-gray-400 text-gray-500 text-sm italic"><i class="fas fa-calendar-days"> </i> {{ post.createdAt|format_datetime(locale='it', pattern="EEEE dd MMMM YYYY | HH:mm")}}</div>
                        <div class="">{{ post.content | u.truncate(90, '...') | raw }}</p>
                    </li>
                {% endfor %}
            </ul>
            <div class="my-6">
                <a class="home-see-all font-semibold" type="" href={{ path('app_post') }}><p class="text-center text-lg">Vedi tutto <i class="ml-2 fas fa-arrow-right"></i></p></a>
            </div>
        </div>
    </section>
{% endblock %}